### ISSUE TITLE
fix time display in events view

### ISSUE THREAD

**Issue by benleb** [wannundwo/wuw_client#36]
WRONG:

> **Mehr Demokratie – Bürger bestimmen sich selbst!**
> 03.12.2015 17:30 Uhr - 03.12.2015 17:30 Uhr
> Aula, Bau 1, HFT Stuttgart

RIGHT:

> Vortrag im Rahmen des Ethikums
> **Mehr Demokratie – Bürger bestimmen sich selbst!**
> 03.12.2015, 17:30 Uhr
> Aula, Bau 1, HFT Stuttgart

**Comment by zirkler** [comment]
fixed by 0df82a6aaf42ad810ddceeea734ebea548793eac
