### ISSUE TITLE
deadlines: What to do with deadlines from the past?

### ISSUE THREAD

**Issue by zirkler** [wannundwo/wuw_client#8]

**Comment by benleb** [comment]
maybe we should use this feature http://docs.mongodb.org/manual/core/index-ttl/ :+1:

**Comment by benleb** [comment]
@TheJetlag !?

**Comment by TheJetlag** [comment]
Sounds like a job for the bad weather weekend. :beers:

**Comment by zirkler** [comment]
We simply don't show them.
